


#ifndef MODBUS_DEBUG_DEFINES_H
#define MODBUS_DEBUG_DEFINES_H


//#define MODBUS_DEBUG_READ_REGISTER_GET_DATA
//#define MODBUS_DEBUG_READ_COIL
//#define MODBUS_DEBUG_WRITE_COIL
#define MODBUS_DEBUG_WRITE_REGISTER


#define MODBUS_DEBUG_RELAIS_SET
//#define MODBUS_DEBUG_RELAIS_GET



#endif /* MODBUS_DEBUG_DEFINES_H */
