


#ifndef MODBUS_DEBUG_DEFINES_H
#define MODBUS_DEBUG_DEFINES_H


#define MODBUS_DEBUG_READ_REGISTER_GET_DATA
#define MODBUS_DEBUG_READ_COIL
#define MODBUS_DEBUG_WRITE_COIL
#define MODBUS_DEBUG_WRITE_REGISTER


#define MODBUS_DEBUG_RELAIS_SET
#define MODBUS_DEBUG_RELAIS_GET

//Section DHT22
#define MODBUS_DEBUG_DHT22

//Section One wire
#define MODBUS_DEBUG_TEMP_SENSOR_ONE_WIRE

//Section light intensity element
#define MODBUS_DEBUG_LIGHT_INTENSITY_ELEMENT

//Section presence detector element
#define MODBUS_DEBUG_PRESENCE_DETECTOR_ELEMENT



#endif /* MODBUS_DEBUG_DEFINES_H */
